/**
 * Mock data for Edit Management table
 * Can be replaced with actual API data
 */

export const claimsData = [
  {
    id: '0028',
    visitNumber: '140201',
    date: 'Aug 26, 2025',
    time: '8:36 PM',
    timeElapsed: '8m ago',
    provider: 'MOI Teaching and Referral Hospital',
    benefitType: 'OPD',
    benefitName: 'General Consultation & Treatment',
    diagnosis: 'Headache, Migraine Assessment',
    decision: 'MODIFIED & APPROVED',
  },
  {
    id: '0029',
    visitNumber: '140202',
    date: 'Aug 27, 2025',
    time: '9:15 AM',
    timeElapsed: '8m ago',
    provider: 'MOI Teaching and Referral Hospital',
    benefitType: 'DENTAL',
    benefitName: 'Dental Care & Services',
    diagnosis: 'Orthodontic Assessment',
    decision: 'APPROVED',
  },
  {
    id: '0030',
    visitNumber: '140203',
    date: 'Aug 28, 2025',
    time: '2:30 PM',
    timeElapsed: '8m ago',
    provider: 'MOI Teaching and Referral Hospital',
    benefitType: 'OPTICAL',
    benefitName: 'Eye Care & Vision Services',
    diagnosis: 'Refractive Error, Glasses',
    decision: 'REJECTED',
  },
  {
    id: '0031',
    visitNumber: '140204',
    date: 'Aug 29, 2025',
    time: '11:45 AM',
    timeElapsed: '8m ago',
    provider: 'MOI Teaching and Referral Hospital',
    benefitType: 'OPD',
    benefitName: 'General Consultation & Treatment',
    diagnosis: 'Respiratory Tract Infection',
    decision: 'DECISION PENDING',
  },
  {
    id: '0032',
    visitNumber: '140205',
    date: 'Aug 30, 2025',
    time: '3:20 PM',
    timeElapsed: '8m ago',
    provider: 'MOI Teaching and Referral Hospital',
    benefitType: 'DENTAL',
    benefitName: 'Dental Care & Services',
    diagnosis: 'Tooth Extraction, Oral Surgery',
    decision: 'DECISION PENDING',
  },
  {
    id: '0033',
    visitNumber: '140206',
    date: 'Aug 31, 2025',
    time: '10:15 AM',
    timeElapsed: '8m ago',
    provider: 'Kenyatta National Hospital',
    benefitType: 'OPD',
    benefitName: 'General Consultation & Treatment',
    diagnosis: 'Headache, Migraine Assessment',
    decision: 'APPROVED',
  },
  {
    id: '0034',
    visitNumber: '140207',
    date: 'Sep 1, 2025',
    time: '2:45 PM',
    timeElapsed: '8m ago',
    provider: 'Kenyatta National Hospital',
    benefitType: 'OPTICAL',
    benefitName: 'Eye Care & Vision Services',
    diagnosis: 'Eye Infection Treatment',
    decision: 'REJECTED',
  },
  {
    id: '0035',
    visitNumber: '140208',
    date: 'Sep 2, 2025',
    time: '9:30 AM',
    timeElapsed: '8m ago',
    provider: 'Aga Khan University Hospital',
    benefitType: 'DENTAL',
    benefitName: 'Dental Care & Services',
    diagnosis: 'Dental Caries, Root Canal',
    decision: 'DECISION PENDING',
  },
  {
    id: '0036',
    visitNumber: '140209',
    date: 'Sep 3, 2025',
    time: '4:10 PM',
    timeElapsed: '8m ago',
    provider: 'Aga Khan University Hospital',
    benefitType: 'OPD',
    benefitName: 'General Consultation & Treatment',
    diagnosis: 'Respiratory Tract Infection',
    decision: 'APPROVED',
  },
  {
    id: '0037',
    visitNumber: '140210',
    date: 'Sep 4, 2025',
    time: '11:25 AM',
    timeElapsed: '8m ago',
    provider: 'The Nairobi Hospital',
    benefitType: 'OPTICAL',
    benefitName: 'Eye Care & Vision Services',
    diagnosis: 'Glaucoma Screening',
    decision: 'MODIFIED & APPROVED',
  },
];

export const statsData = {
  totalClaims: 53,
  editDone: 35,
  editPending: 18,
};
